/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.community;
import models.doctor;
import models.patient;
import static mrmapp.MRMApp.cities;
import static mrmapp.MRMApp.communities;
import static mrmapp.MRMApp.doctors;
import static mrmapp.MRMApp.hospitals;
import static mrmapp.MRMApp.patUserName;
import static mrmapp.MRMApp.patients;

/**
 *
 * @author kcsar
 */
public class viewItemsPage extends javax.swing.JFrame {

    /**
     * Creates new form viewItemsPage
     */
    public viewItemsPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jlHeading = new javax.swing.JLabel();
        jlHeader = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnCreate.setText("Create New");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jlHeader.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(jlHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlHeading))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnEdit)
                    .addComponent(btnCreate)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        if(jlHeader.getText() == "Cities"){
        this.hide();
        createCity ct = new createCity();
        ct.show();
        }
        else if (jlHeader.getText() == "Hospitals"){
        this.hide();
        createHospital crh = new createHospital();
        for(int i=0;i<cities.size();i++) {
               crh.jcCity.addItem(cities.get(i));
        }
        crh.show();
        }
        else if(jlHeader.getText() == "Communities"){
            this.hide();
            createCommunity cc = new createCommunity();
            for(int i=0;i<cities.size();i++) {
              cc.jcCity.addItem(cities.get(i));
        }
            cc.show();
        }
        else if(jlHeader.getText() ==  "Hospitals"){
            createHospital ch = new createHospital();
        ch.jcCommunity.removeAllItems();
        for (HashMap.Entry<String, community> set : communities.entrySet()) {
            String cityName = set.getValue().getCityName();
            if(ch.jcCity.getSelectedItem().toString().equals(cityName)) {
                ch.jcCommunity.addItem(set.getValue().getName());
            }
        }
        ch.show();
        }
        else if(jlHeader.getText() == "Patients"){
            this.hide();
            createPatient cp = new createPatient();
            cp.jcCity.removeAll();
            for(int i=0;i<cities.size();i++) {
                cp.jcCity.addItem(cities.get(i));
            }
        cp.show();
        }

        else if(jlHeader.getText() == "Doctors"){
            this.hide();
            createDoc doc = new createDoc();
            for(int i=0;i<cities.size();i++) {
                doc.jcCity.addItem(cities.get(i));
            }
            doc.show();
        }
        else if(jlHeader.getText() == "Community Admin"){
            this.hide();
            createCommunityAdmin ca = new createCommunityAdmin();
            for(int i=0;i<cities.size();i++) {
                ca.jcCity.addItem(cities.get(i));
            }
            ca.show();
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.hide();
        systemAdminDashboard sd = new systemAdminDashboard();
        sd.show();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tableModel = (DefaultTableModel) jTable2.getModel();
        if(jTable2.getSelectedRowCount() == 1) {
            if(jlHeader.getText() == "Doctors") {
                int id = Integer.parseInt(tableModel.getValueAt(jTable2.getSelectedRow(), 0).toString());
                for (HashMap.Entry<String, doctor> set : doctors.entrySet()) {
                    if(set.getValue().getDoctorID() == id) {
                        doctors.remove(set.getKey());
                        tableModel.removeRow(jTable2.getSelectedRow());
                    }
                }
            } 
            else if(jlHeader.getText() == "Patients") {
                int id = Integer.parseInt(tableModel.getValueAt(jTable2.getSelectedRow(), 0).toString());
                for (HashMap.Entry<String, patient> set : patients.entrySet()) {
                    if(set.getValue().getPatientId()== id){
                        patients.remove(set.getKey());
                        tableModel.removeRow(jTable2.getSelectedRow());
                    }
                }
            }
            else if(jlHeader.getText() == "Hospitals") {
                String name = tableModel.getValueAt(jTable2.getSelectedRow(), 0).toString();
                hospitals.remove(name);
                tableModel.removeRow(jTable2.getSelectedRow());
                for (HashMap.Entry<String, doctor> set1 : doctors.entrySet()) {
                    if(set1.getValue().getHospitalName().equals(name)) {
                        doctors.remove(set1.getKey());
                    }
                }
            }
        }
        else {
            if(jTable1.getSelectedRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "The table is empty or select a row.");
            }
            else {
                JOptionPane.showMessageDialog(this, "Select one row at a time.");
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if(jlHeader.getText().equals("Patients")){
        DefaultTableModel tableModel = (DefaultTableModel) jTable2.getModel();
        int id = Integer.parseInt(jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString());
        
        if(jTable2.getSelectedRowCount() == 1){
            createPatient cp = new createPatient();
            cp.show();
            cp.tfFirstName.setText(patients.get(patUserName).getFirstName());
            cp.tfUserName.setText(patients.get(patUserName).getUsername());
            cp.tfAge.setText(Integer.toString(patients.get(patUserName).getAge()));
//          cd.jcGender.setSelectedItem(doctors.get(id).getGender());
            cp.tfLastName.setText(patients.get(patUserName).getLastName());
            cp.tfHouseName.setText(patients.get(patUserName).getHouseName());
            cp.tfDrID.setText(Integer.toString(id));
            cp.tfZipCode.setText(Integer.toString(patients.get(patUserName).getZip()));
        }
            
        }
        
        else if(jlHeader.getText().equals("Doctors")){
        DefaultTableModel tableModel = (DefaultTableModel) jTable2.getModel();
        int id = Integer.parseInt(jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString());
        
        if(jTable2.getSelectedRowCount() == 1){
            createDoc cd = new createDoc();
            cd.show();
            cd.tfName.setText(doctors.get(id).getFirstName());
            cd.tfUserName.setText(doctors.get(id).getUserName());
            cd.tfAge.setText(Integer.toString(doctors.get(id).getAge()));
//          cd.jcGender.setSelectedItem(doctors.get(id).getGender());
            cd.tfLastname.setText(doctors.get(id).getLastName());
            cd.tfHouseName.setText(doctors.get(id).getHouseName());
            cd.tfDocID.setText(Integer.toString(id));
            cd.tfZipCode.setText(Integer.toString(doctors.get(id).getZip()));
            cd.show();
        }
        }
            
        
        if(jlHeader.getText().equals("Hospital")){
        DefaultTableModel tableModel = (DefaultTableModel) jTable2.getModel();
        int id = Integer.parseInt(jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString());
        
        if(jTable2.getSelectedRowCount() == 1){
            createHospital ch = new createHospital();
            ch.show();
            ch.tfName.setText(hospitals.get(id).getHospitalName());
            ch.tfZip.setText(Integer.toString(hospitals.get(id).getZip()));
        }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    /**
     * @param args the command line arguments
     */
        public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewItemsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewItemsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewItemsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewItemsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewItemsPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCreate;
    public javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    public javax.swing.JTable jTable2;
    public javax.swing.JLabel jlHeader;
    private javax.swing.JLabel jlHeading;
    // End of variables declaration//GEN-END:variables
}
